### PR TITLE
check for explicit config files

### LINKED ISSUE #116: If config file isn't found, voctocore silently ignores it without any warning or anything
Run `./voctocore/voctocore.py -v -i config.inii` and wonder why voctomix isn't using your configuration. Some type of error message would be nice.

### PR DESCRIPTION
**Pull request by MaZderMind**
fixes #116

### CODE REVIEW

**Comment by MaZderMind** [comment]
@Florob thank you for your feedback, changed the PR accordingly

**Comment by Florob** [comment]
I have to say I don't find the output terribly convincing:
```
Traceback (most recent call last):
  File "./voctocore.py", line 101, in <module>
    main()
  File "./voctocore.py", line 94, in main
    voctocore = Voctocore()
  File "./voctocore.py", line 41, in __init__
    from lib.pipeline import Pipeline
  File "/home/florian/devel/voctomix/voctocore/lib/pipeline.py", line 5, in <module>
    from lib.config import Config
  File "/home/florian/devel/voctomix/voctocore/lib/config.py", line 40, in <module>
    'could not be read', Args.ini_file)
RuntimeError: ('explicitly requested config-file "%s" could not be read', 'foobar')
```
It might make sense to just call `log.error()` and `sys.exit(1)`.

**Comment by MaZderMind** [comment]
@Florob I'd rather have a top-level error-handler catching RuntimeErrors and printing a nice red error message before terminating. If you don't mind I'll try to add that.

**Comment by Florob** [comment]
I don't mind that. The string formatting should probably still happen here already, instead of retrofitting semantics onto `RuntimeError`

**Comment by MaZderMind** [comment]
Oh, yes, missed that part. Sure, there's a .format missing here.

**Comment by MaZderMind** [comment]
@Florob  screenshot from 2017-08-08 21-25-49

**Comment by Florob** [comment]
This seems nice. Voctogui's `config.py` still doesn't perform the same check even though the exception is caught.

**Comment by MaZderMind** [comment]
@Florob I modified the PR to also do the check for voctogui. It currently requires modifying the import-order, which makes the code a little bit messy. With the Unit-Test PR I'll extract out of #139 this will be fixed by having an actual `load()`-method for the config, so the import-order does not matter anymore.

Furthermore I'd love to hear your thought on #146. I'm so done with this code duplication.

**Pull request merged**
