### PR TITLE
allow audio and video only streams

### PR DESCRIPTION
**Pull request by DavidVentura**
This addresses part of my performance related "bug" (#127).
It seems that removing the unnecessary streams + the unnecessary generation of videotestsrc and audiotestsrc that were fed to comply with the required caps helps a lot.

I added two options to the config `audio_only` and `video_only`, which are lists representing which sources do not have audio/video. These are optional and if not present the behavior stays the same as it was until now.

When trying to set an audio_only source as video, nothing happens, it will just render the background image if present (black if there's no background feed)

When trying to set a video_only source as audio, there's no audio at all.

PS: My personal config and motivation to do this:

```ini
sources=slides,cam1,cam2,audio1,audio2,video
audio_only=audio1,audio2
video_only=slides,cam1,cam2
```
I only get a mixed stream from `video`

### CODE REVIEW

**Comment by Florob** [comment]
Thanks for working on this. In general I think audio and video only sources are a sensible concept.

However, I'm not sure how this patch is even working for you. It breaks the fundamental assumption that there is a bijection between source id and source name. With this patch applied videomix, audiomix and every thing else have three separate views on the source id.
In your setup in particular running `set_audio audio1` will actually mute all channels, because it sets the audio to source id 3, but only sources 0 and 1 exist according to audiomix.
You are probably running `set_audio 0`, which is going to go away as per #98, or relying on changes made in #130.

Ideally this would also go along with voctogui changes so audio-only sources aren't offered as video inputs. More generally I'd want voctocore to report an error when setting a video input to a audio-only source and vice versa.

**Comment by DavidVentura** [comment]
Currently this works for me using multiple audio sources and controlling them by name. I might've missed a commit in the branch. I'll look into it and report back.


On July 14, 2017 8:12:30 AM GMT-03:00, Florob <notifications@github.com> wrote:
>Thanks for working on this. In general I think audio and video only
>sources are a sensible concept.
>
>However, I'm not sure how this patch is even working for you. It breaks
>the fundamental assumption that there is a bijection between source id
>and source name. With this patch applied videomix, audiomix and every
>thing else have three separate views on the source id.
>In your setup in particular running `set_audio audio1` will actually
>mute all channels, because it sets the audio to source id 3, but only
>sources 0 and 1 exist according to audiomix.
>You are probably running `set_audio 0`, which is going to go away as
>per #98, or relying on changes made in #130.
>
>Ideally this would also go along with voctogui changes so audio-only
>sources aren't offered as video inputs. More generally I'd want
>voctocore to report an error when setting a video input to a audio-only
>source and vice versa.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/voc/voctomix/pull/128#issuecomment-315334860

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by MaZderMind** [comment]
This feature is now in master. Please re-open the corresponding issue if you still see an issue.

**Comment by MaZderMind** [comment]
sorry, misread the title

**Comment by DavidVentura** [comment]
@Florob  I'll try again and get this working. I "rebased" on top of master, with some changes.
My idea was to have VideoMix only know about streams that have video and AudioMix to know about the streams that have audio, this means that the commands may only display this sublists when querying about `video_status` and `audio_status`

Do you think this is the right approach? or would you approach this in some other way?

**Comment by MaZderMind** [comment]
This PR has not seen any activity for a couple of months and is not mergable. As @Florob mentioned it is not really compatible with the current enumeration schema in the command line protocol.

**Pull request closed without merging**
