### PR TITLE
Voctolight

### PR DESCRIPTION
**Pull request by JulianJacobi**
cleanup voctolight scripts and fix some voctolight issues

### CODE REVIEW

**Comment by MaZderMind** [comment]
@JulianJacobi is this PR ready to be merged or still WiP?

**Comment by MaZderMind** [comment]
@JulianJacobi ping

**Comment by JulianJacobi** [comment]
This Request is Ready to be merged. It's tested and working better than the actual version in this repo.
Mainly it fixes problem with different composite modes.

**Comment by MaZderMind** [comment]
github seems to be slightly confused, but this pr has been merged in fecf5e4504260f6dabf23372543384f74a527f06

**Pull request closed without merging**
