### PR TITLE
add facebook streaming example

### LINKED ISSUE #160: Streaming to Facebook Live
Create example scripts for streaming to Facebook live

### PR DESCRIPTION
**Pull request by crossan007**
closes #160

### CODE REVIEW

**Comment by markvdb** [comment]
As far as I know, the average web user cannot receive these live broadcasts through facebook without logging in to the facebook ecosystem. (I might be mistaken about that, but that's how it looks to me at first sight.) It might be a good idea to at the very least clearly label this outcast non-free. That should help with the Debian packaging.

Things would be less murky with a public youtube outcast. A public youtube broadcast is at least publicly available without jumping through hoops.

**Comment by a-tze** [comment]
I'm not sure how an example script for a non-public streaming service could lead to problems with Debian packaging. 
In the belief the author tested this and it works, LGTM.

**Comment by crossan007** [comment]
I can do some more testing and tweaks on this as discussed in IRC if you're OK leaving this PR open for a while until it's *production* ready.

**Comment by MaZderMind** [comment]
Would you mind documenting the communication in IRC here? I'm currently not actively reading IRC but would be interested in the tasks to do.
I also don't see a reason not to merge this. The example-scripts is only codified documentation.

**Comment by crossan007** [comment]
I agree with @MaZderMind  - go ahead and merge this.   I'll submit more PRs if I make improvements.

**Comment by crossan007** [comment]
I agree with @MaZderMind - go ahead and merge this. I'll submit more PRs if I make improvements.

**Pull request merged**
