### PR TITLE
voctogui: add presets tab to gui

### PR DESCRIPTION
**Pull request by Kunsi**
TODO: Figure out how to properly show the previous selection.

### CODE REVIEW

**Comment by sophieschi** [comment]
Note: only show presets for transisions that exist.

**Comment by Kunsi** [comment]
Tested, works as intended. Planning to merge this for 2.1

**Comment by Kunsi** [comment]
TODO: find out why keybindings don't work
TODO: add documentation and/or example config

**Comment by Kunsi** [comment]
This accidentially also fixes #304 and #275 apparently.

**Pull request merged**
