### PR TITLE
Feature/config window size

### LINKED ISSUE #150: Option for Window-Size in Voctogui
Add an option to configure the default window-size in voctogui
also see #69

### PR DESCRIPTION
**Pull request by fightling**
fixed #150 and #69 

syntax within the configuration (ini) file is:

```
# new section
[mainwindow]

# resize main window
width=1700
height=1000

# force main window to stay full screen
forcefullscreen=true
```

**Hint**: `force_fullscreen` was renamed later into `forcefullscreen`

### CODE REVIEW

**Comment by fightling** [comment]
did some code review... canceling this request and adding a new one

**Comment by fightling** [comment]
decided to continue here.

**Comment by fightling** [comment]
I think I would merge this request now. Adding x and y to set window position can be made but is usually up to the window manager. what do you think? 

Any further suggestions?

And excuse me for bringing all that tension of my learning curve into the commit history :grin:

**Comment by MaZderMind** [comment]
Wouldn’t it be better to completely disable resizing if any if the tree options are set? I would expect the config options do disable manual resizing.
This would also remove the need for the on-resize callback, which has a bad smell to me.

**Comment by fightling** [comment]
Good idea to make the window un-resizable when width/height is used. But full screen state is just not affected by this :/

**Pull request merged**
